#!/usr/bin/env node
var fs = require("fs");
const nameFile = process.argv[2];
const currDir = process.argv[1].replace("/directories2file", "");

function readLoopDir(dir, prev, acc) {
    let _acc = `${acc}/${dir}`;
    fs.readdir(prev, (err, files) => {
        if (err) throw err;
        if (files.length === 0) {
            const data = _acc.replace(`/${nameFile}/`, '').replace(/\//g, '').replace(/\|/g, '/');
            let p = new Buffer.from(data, 'base64').toString('binary')
            process.chdir(currDir);

            fs.writeFile(
                `${nameFile}_`,
                p, 'binary', (err) => {
                    if (err) throw err;
                });

        }
        files.filter(ch => {
            if (fs.existsSync(`${prev}/${ch}`)) {
                process.chdir(dir);
                readLoopDir(ch, files[0], _acc);
            }
        });
    })
}

readLoopDir(nameFile, nameFile, '');

