#!/usr/bin/env node
/*
ISC License

Copyright (c) 2019-2020 Vincenzo Tilotta

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/
const fs = require("fs");
const nameDir = process.argv[2];
const currDir = process.cwd();
const internationalization = require("./i18n/language");
const language = internationalization.i18n();

if (process.argv.length < 3) {
    console.error(language.LIMITPARAM);
    process.exit(1);
}

const readLoopDir = async (dir, prev, acc) => {
    const _acc = `${acc}/${dir}`;
    fs.readdir(prev, (err, files) => {
        if (err) throw err;
        if (files.length === 0) {
            const data = _acc.replace(`/${nameDir}/`, '').replace(/\//g, '').replace(/\|/g, '/');
            const p = new Buffer.from(data, 'base64').toString('binary');
            const fileName = nameDir.replace(/\//g, '');
            process.chdir(currDir);

            fs.writeFile(
                `new_${fileName}`,
                p, 'binary', (err) => {
                    if (err) throw err;
                });

        }
        files.filter(ch => {
            if (fs.existsSync(`${prev}/${ch}`)) {
                process.chdir(dir);
                readLoopDir(ch, files[0], _acc);
            }
        });
    })
}

readLoopDir(nameDir, nameDir, '');
