#!/usr/bin/env node
/*
ISC License

Copyright (c) 2019 Vincenzo Tilotta

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/
var fs = require("fs");

function createLoopDir(base, str) {
    const sp = str.split('/');
    let acc = '';
    sp.forEach((elem) => {
        if (elem === '') {
            acc = '_';
        } else {
            acc = `${elem}`;
        }
        if (!fs.existsSync(acc)) {
            fs.mkdirSync(acc);
            process.chdir(acc);
        }
    });
}

fs.readFile(process.argv[2], "utf8", function (err, data) {
    if (err) throw err;
    const dn = `_${process.argv[2]}`;
    if (!fs.existsSync(dn)) {
        fs.mkdirSync(dn);
        process.chdir(dn);
    }
    const f = Buffer.from(data, 'binary').toString('base64').match(/.{1,130}/g);
    if (fs.existsSync(f[0])) { return false; }
    f.forEach((element) => {
        createLoopDir(dn, element);
    });
    return true;
});
